apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  namespace: elastic-system
  labels:
    type: local
spec:
  capacity:
   storage: 15Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data"
