apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.13.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic-system
