apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: demo05
  labels:
    app: nginx
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
