apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-resolver
  name: nginx-resolver
  namespace: demo05
spec:
  containers:
  - image: nginx
    name: nginx-resolver
    ports:
    - containerPort: 80
