apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
  namespace: demo05
spec:
  selector:
    app.kubernetes.io/name: nginx-resolver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
