apiVersion: v1
kind: Pod
metadata:
  name: super-pod
  namespace: demo05
spec:
  containers:
  - name: super-pod
    image: busybox
    command: ["sleep","4800"]
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
