apiVersion: v1
kind: Pod
metadata:
  name: admin-pod
  namespace: demo06
spec:
  containers:
  - name: admin-pod
    image: busybox
    command: 
    - "sleep"
    - "3200"
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
