apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-003
  name: web-003
  namespace: demo06
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-003
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-003
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
