apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cm01-pod
spec:
  containers:
  - name: ubuntu-cm01-container
    image: ubuntu
    command: ["sleep"]
    args: ["360"]
    env:
      - name: APP_SIZE 
        valueFrom:
          configMapKeyRef:
            name: configmap-env
            key: APP_SIZE
