apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cm02-pod
spec:
  containers:
  - name: ubuntu-cm02-container
    image: ubuntu
    command: ["sleep"]
    args: ["360"]
    envFrom:
      - configMapRef:
          name: configmap-env
