apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontendnew
  template:
    metadata:
      labels:
        tier: frontendnew
    spec:
      containers:
      - name: php-redis
        image: nginx
