apiVersion: v1
kind: Service
metadata:
  name: nginx-service-w02
spec:
  type: NodePort
  selector:
    app: nginx-deploy-w02
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
